import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// I1 -> 25:5
// I2 -> 25:5 
// I3 -> 25:10
const Home: NextPage = () => {
  const isTimeCounted: boolean = false;

  const timer = "00:00";

  return (
    <div className={styles.container}>
      <Head>
        <title>Poomkun Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heading}>
          <h1>Poomkun Pomodoro</h1>
        </div>
        <div className={styles.timer}>
          <h2>Timer</h2>
          <h2>{timer}</h2>
          <div>
            <button>Play</button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
